### ISSUE TITLE
Download freezes

### ISSUE THREAD

**Issue by imatnanohara** [patchzyy/WheelWizard#10]
I try installing and the downloads freezes after a while and just stops installing completely, I already tried multiple times, the application also freezes and stops working completely.
![image_2024-07-13_213931979](https://github.com/user-attachments/assets/3b6b2092-6839-4f98-8e3f-e9568808cbe8)

**Comment by ABCCBAYXZ** [comment]
Due to the slow download speed, I recommend installing Retro Rewind manually. The download is available on Tockdom: wiki.tockdom.com/wiki/Retro_Rewind. After downloading, the ZIP file must be extracted. Then the folder "RetroRewind6" must be copied to the folder C:\Users\<username>\AppData\Roaming\Dolphin Emulator\Load\Riivolution. Replace <username> with your actual Windows user name.

After restarting WheelWizard, only an update needs to be installed, which should be completed within a few minutes.

**Comment by patchzyy** [comment]
Updated servers, download speeds should be faster now
